server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /user-center/**
      serviceId: user-center
